name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: Test
      run: dotnet test
    - name: Generate build number
      uses: einaregilsson/build-number@v1 
      with:
        token: ${{secrets.github_token}}        
    - name: Pack and publish
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      run: |
        VERSION=$(date '+%Y.%m.%d').$BUILD_NUMBER
        dotnet pack -c RELEASE -p:Version=$VERSION -o out/
        dotnet nuget push out/CsfdAPI.$VERSION.nupkg -k $NUGET_API_KEY -s https://api.nuget.org/v3/index.json
