name: .NET Core

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    - name: Test
      run: dotnet test

    - name: Pack and publish
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      run: |
        VERSION=$(date '+%Y.%-m.%-d').$GITHUB_RUN_NUMBER
        dotnet pack -c RELEASE -p:Version=$VERSION
        dotnet nuget push CsfdAPI/bin/Release/CsfdAPI.$VERSION.nupkg -k $NUGET_API_KEY -s https://api.nuget.org/v3/index.json
