name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100
    - name: Test
      run: dotnet test
    - name: Pack and publish
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      run: |
        VERSION=$(date '+%Y.%m.%d').${GITHUB_SHA:0:6}
        dotnet pack -c RELEASE -p:Version=$VERSION -o out/
        dotnet push out/CsfdAPI.$VERSION.nupkg -k $NUGET_API_KEY
